services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: polls
      POSTGRES_USER: polls
      POSTGRES_PASSWORD: polls
    ports:
      - "127.0.0.1:5432:5432"
